# Prétraitement et Construction du Dataset

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path(".").resolve().parent if Path(".").resolve().name == "notebooks" else Path(".").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.data.preprocessing import DatasetBuilder

In [2]:
builder = DatasetBuilder(project_root=PROJECT_ROOT, random_state=42)

summary_df = builder.build_dataset()

1. Récupération des fichiers valides...
2. Exécution du split stratifié (70/15/15)...
3. Préparation des répertoires...
4. Traitement et copie des images...

  0%|          | 0/14055 [00:00<?, ?it/s]

5. Génération du data_summary.csv...
Pipeline de prétraitement terminé avec succès ! ✅

### Audit

In [3]:
print(f"Total d'images conservées dans processed : {len(summary_df)}")
display(summary_df.sample(5))

Total d'images conservées dans processed : 14055

,filepath,class,source,split
10979,data/processed/val/Corn___Gray_Leaf_Spot/Corn_...,Corn___Gray_Leaf_Spot,CCMT,val
9397,data/processed/train/Cassava___Brown_Spot/Cass...,Cassava___Brown_Spot,CCMT,train
4907,data/processed/train/Corn___Gray_Leaf_Spot/Cor...,Corn___Gray_Leaf_Spot,PV,train
6978,data/processed/train/Corn___Gray_Leaf_Spot/Cor...,Corn___Gray_Leaf_Spot,CCMT,train
8287,data/processed/train/Corn___Northern_Leaf_Blig...,Corn___Northern_Leaf_Blight,CCMT,train

In [4]:
# Répartition Train/Val/Test
split_counts = summary_df.groupby(['class', 'split']).size().unstack(fill_value=0)

# Réorganisation des colonnes dans un ordre logique
split_counts = split_counts[['train', 'val', 'test']]
split_counts['total'] = split_counts.sum(axis=1)

# Calcul des pourcentages réels post-stratification
split_counts['train_%'] = (split_counts['train'] / split_counts['total'] * 100).round(1)
split_counts['val_%'] = (split_counts['val'] / split_counts['total'] * 100).round(1)
split_counts['test_%'] = (split_counts['test'] / split_counts['total'] * 100).round(1)

display(split_counts)

split                        train  val  test  total  train_%  val_%  test_%
class
Cassava___Bacterial_Blight    1830  392   392   2614     70.0   15.0    15.0
Cassava___Brown_Spot          1037  222   222   1481     70.0   15.0    15.0
Cassava___Healthy              835  179   179   1193     70.0   15.0    15.0
Cassava___Mosaic               843  181   181   1205     70.0   15.0    15.0
Corn___Common_Rust             834  179   179   1192     70.0   15.0    15.0
Corn___Fall_Armyworm           200   43    42    285     70.2   15.1    14.7
Corn___Gray_Leaf_Spot         1233  264   265   1762     70.0   15.0    15.0
Corn___Healthy                 958  205   205   1368     70.0   15.0    15.0
Corn___Northern_Leaf_Blight   1388  297   298   1983     70.0   15.0    15.0
Corn___Streak_Virus            680  146   146    972     70.0   15.0    15.0